name: Flutter Web

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{ secrets.ACCESS_TOKEN }}
      #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.x" # you can use 1.12
          channel: "beta" # Currently you have to use beta channel for Flutter web.
      - name: Build Test cases
        run: flutter test
      - name: Enable Web
        run: flutter config --enable-web
        working-directory: .
      - name: Install Dependencies
        run: flutter packages get -v
        working-directory: .
      - name: Build Web
        run: flutter build web -v
        working-directory: .
      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email prakash@sutara.org
          git config --global user.name  bhanugummana
          git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/chimple/malta.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Updated docs"
          #git push --force secure-origin gh-pages
          #git push --set-upstream origin gh-pages
          git push origin gh-pages -f
